models/store.py
from models.model import Model
import uuid
from typing import Dict
import re
from dataclasses import dataclass, field


@dataclass(eq=False)
class Store(Model):
    collection: str = field(init=False, default="stores")
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=uuid.uuid4().hex)

    def json(self):
        return {
            "_id": self._id,
            "name": self.name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "query": self.query
        }

    @classmethod
    def get_by_name(cls, store_name: str):
        return cls.find_one_by("name", store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str):
        url_regex = {"$regex": "^{}".format(url_prefix)}
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def find_by_url(cls, url: str):
        pattern = re.compile(r"(https?://.*?/)")
        match = pattern.search(url)
        url_prefix = match.group(1)

        return cls.get_by_url_prefix(url_prefix)

views/stores.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.store import Store
from models.user import requires_admin, requires_login
import json

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
@requires_login
def index():
    stores = Store.all()
    return render_template('stores/index.html', stores=stores)


@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_admin
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store = Store(name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')

@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('stores.index'))

    return render_template('stores/edit_store.html', store=store, query=json.dumps(store.query))

@store_blueprint.route('/delete/<string:store_id>')
@requires_admin
def delete_store(store_id):
    store = Store.get_by_id(store_id)
    store.remove_from_mongo()

    return redirect(url_for('.index'))

templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Create Store</h1></header>
    <section class="create-store-form">
        <form method="POST">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" class="form-control" name="name" placeholder="Store Name" value="{{ store.name }}" />
            </div>
            <div class="form-group">
                <label for="url_prefix">url_prefix</label>
                <input type="text" id="url_prefix" class="form-control" name="url_prefix" placeholder="https://" value="{{ store.url_prefix }}" aria-describedby="urlPrefixHelp" />
                <small class="form-text text-muted" id="urlPrefixHelp">
                    What URL will all of the store's items start with?
                </small>
            </div>
            <div class="form-group">
                <label for="tag_name">HTML Tag Name</label>
                <input type="text" id="tag_name" class="form-control" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="tagNameHelp" />
                <small class="form-text text-muted" id="tagNameHelp">
                    What HTML tag contains the price information for items in this store?
                </small>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" id="query" class="form-control" name="query" placeholder='{"class": "price"}' value="{{ query }}" aria-describedby="queryHelp" />
                <small class="form-text text-muted" id="queryHelp">
                    What query will identify the proper tag containing the price?
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </section>
{% endblock %}

templates/stores/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1>Stores</h1>
</header>
<section>
    <div class="list-group mb-3">
        {% for store in stores %}
            <div class="list-group-item">
                <h4 class="list-group-item-heading">{{ store.name }}</h4>
                <p>
                    For URLs starting with {{ store.url_prefix }}
                </p>
                {% if session['email'] == config.ADMIN %}
                <a class="btn btn-secondary" href="{{ url_for('stores.edit_store', store_id=store._id) }}">
                    Edit
                </a>
                <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}">
                    Delete
                </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    {% if session['email'] == config.ADMIN %}
    <a class="btn btn-primary" href="{{ url_for('stores.create_store') }}">Create New</a>
    {% endif %}
</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Create Store</h1></header>
    <section class="create-store-form">
        <form method="POST" action="/stores/new">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" class="form-control" name="name" placeholder="Store Name"/>
            </div>
            <div class="form-group">
                <label for="url_prefix">url_prefix</label>
                <input type="text" id="url_prefix" class="form-control" name="url_prefix" placeholder="https://" aria-describedby="urlPrefixHelp" />
                <small class="form-text text-muted" id="urlPrefixHelp">
                    What URL will all of the store's items start with?
                </small>
            </div>
            <div class="form-group">
                <label for="tag_name">HTML Tag Name</label>
                <input type="text" id="tag_name" class="form-control" name="tag_name" placeholder="span" aria-describedby="tagNameHelp" />
                <small class="form-text text-muted" id="tagNameHelp">
                    What HTML tag contains the price information for items in this store?
                </small>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" id="query" class="form-control" name="query" placeholder='{"class": "price"}' aria-describedby="queryHelp" />
                <small class="form-text text-muted" id="queryHelp">
                    What query will identify the proper tag containing the price?
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </section>
{% endblock %}