views/users.py
from flask import Blueprint, render_template, redirect, request, session, url_for, flash
from models.user import User, UserErrors
import re

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            User.register_user(email, password)
            session['email'] = email
            return redirect(url_for('alerts.index'))

        except UserErrors.UserError as e:
            flash('We already have you in the system, log in below!', 'warning')
            return redirect(url_for('users.login_user'))

    return render_template('users/register.html')

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                pattern = re.compile(r"^.*(?=(@))")
                match = pattern.search(email)
                name = match.group(0)
                flash('Welcome back, {}!'.format(name), 'success')
                return redirect(url_for('alerts.index'))
        except UserErrors.IncorrectPasswordError as e:
            flash(e.message, 'danger')
        except:
            flash("Looks like you're not registered yet, do it now!", 'warning')
            return redirect(url_for('users.register_user'))

    return render_template('users/login.html')

@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    flash("See you later!", 'success')
    return redirect(url_for('users.login_user'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Price Alerts</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>
        <div class="content container mt-2">
            <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
                <a class="navbar-brand" href="/">Pricing Service</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-between">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('stores.index') }}" class="nav-item nav-link">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('alerts.index') }}" class="nav-item nav-link">Alerts</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if not session['email'] %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.login_user') }}" class="nav-item nav-link">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.register_user') }}" class="nav-item nav-link">Sign up</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.logout_user') }}" class="nav-item nav-link">Log out</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <div class="mt-3">
                {% block content %}
            
                {% endblock %}
            </div>
            
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">Pricing Service</h1>
    <p class="lead">We let you know when your favorite stuff goes on sale!</p>
    <hr class="my-4" />
    <p>Just sign up, then get started by adding the URL of an item that you wish to track - we'll do the rest!</p>
    <a href="{{ url_for('users.register_user') }}" class="btn btn-primary btn-lg">Get started</a>
</div>

{% endblock %}